### ISSUE TITLE
check for default RX/TX queue values in nova.conf

### ISSUE THREAD

**Issue by aserdean** [dosaboy/hotsos#102]
Alert if `nova.conf` doesn't have set: `rx_queue_size`, `tx_queue_size`(DPDK) under `[libvirt]`.
Also alert if the value is under `1024`.

Basically we are looking for the following to be set in `nova.conf` and altert otherwise:
```
[libvirt]
rx_queue_size=1024
tx_queue_size=1024
```

**Comment by dosaboy** [comment]
In order to do this we will need an easy way to detect if dpdk is in use on a node. Any ideas?
