### ISSUE TITLE
bluefs_buffered_io + kernel version check

### ISSUE THREAD

**Issue by lathiat** [dosaboy/hotsos#105]
Warn if bluefs_buffered_io=enable and kernel <5.4 (e.g. non-HWE for bionic): Ceph performance may be affected

bluefs_buffered_io was enabled by default in v13.2.0 and v14.2.0.
bluefs_buffered_io was disabled by default in v14.2.10 and v15.2.0.
bluefs_buffered io was re-enabled in the following point releases:
v14.2.22
v15.2.13
v16.2.0

Reference:
https://docs.google.com/document/d/1uv1Q8p2OR3hG_eEjbpP7OuS3rxmXUgpIlTG5JcpFDaY/edit#

**Comment by pponnuvel** [comment]
Note: only on Ceph deployments that use bcache.

**Comment by dosaboy** [comment]
The tricky thing here is that nodes running osds don't often have the osd config readily available to view (in a sosreport at least) but I think we can start by making this assertion based on package version knowing what defaults exist.

**Comment by pponnuvel** [comment]
Raised https://github.com/sosreport/sos/issues/2613 to add it to sosreport.
I'll make a PR when I get time. If it gets accepted, we'll have the config of every OSD from a mon's sosreport.

If not, the table approach (ceph version mapped its default value of bluefs_buffered_io) is fine. The problem here is that once a customer corrects bluefs_buffered_io, we'll only see false positives from all subsequent sosreports.

**Comment by dosaboy** [comment]
@pponnuvel the ideal would be if we could retrieve the config from an osd node so that we have it all in the same sos but i think that's be tricky due to location of keys. As a minimum we could just print a suggestion to check that bluefs_buffered_io is set to False given the right conditions.

**Comment by pponnuvel** [comment]
@dosaboy We could get from individual OSD hosts, too. `ceph daemon osd.X config show` and the list of OSDs on that host can be retrieved with `mount | awk '/ceph/{l=split($3,a,"/"); split(a[l],b,"-"); print b[2]}'`. So it's possible to do that as well.

The reason I preferred to do from a mon is that we almost always get a sosreport from a mon but not from every single OSD.

Either way, we could get this info to sosreport which would be useful to know all the configs (not just bluefs_buffered_io). The version table can be an [alternative solution](https://dictionary.cambridge.org/dictionary/english/workaround) until this info gets added to sosreport.

**Comment by dosaboy** [comment]
@pponnuvel sure but ceph-mon sos wont tell you the kernel version used on hosts running ceph-osds and also wont tell you if the backing device is (using a) bcache.

**Comment by pponnuvel** [comment]
@dosaboy Yeah, that makes sense. So we could get it added to the OSDs' sosreports then.

**Comment by lathiat** [comment]
Just realised that I think it does. The “ceph report” output from the mon has a lot of per host detail and I think includes the kernel version.

**Comment by dosaboy** [comment]
@lathiat does it tell if the osd is using bcache though? e.g. if the osd is using a dmcrypt device that is backed by a bache.
