### ISSUE TITLE
Validate require_osd_release and v2 messenger bindings

### ISSUE THREAD

**Issue by hillpd** [dosaboy/hotsos#130]
After upgrading to Nautilus, Octopus, or Pacific it is required to run the following command:
`sudo ceph osd require-osd-release {nautilus,octopus,pacific}`

For Nautilus, in particular, this step is critical to prevent communication failures. See the Nautilus release notes [0]:
> This step is mandatory. Failure to execute this step will make it impossible for OSDs to communicate after msgrv2 is enabled.

There are two checks I recommend implementing here:
1. Parse `ceph osd dump` to confirm `require_osd_release` aligns with the ceph major version.
2. Parse `ceph osd dump` and `ceph mon dump` for any mons/osds that are not binding to v2 addresses.

[0] https://docs.ceph.com/en/latest/releases/nautilus/#instructions

**Comment by dosaboy** [comment]
The first part of this is implemented in https://github.com/dosaboy/hotsos/commit/325aca7dbb1305dffd83b0362a692899e0731045
