### ISSUE TITLE
Ceph OSD Map Trimming Warning

### ISSUE THREAD

**Issue by lathiat** [dosaboy/hotsos#131]
Report on ceph_report .osdmap_manifest.pinned_maps list too long

jq '.osdmap_manifest.pinned_maps | length'

$ cat report-0.txt |jq '.osdmap_manifest.pinned_maps | length'

Seems possibly 5000 is 'bad' and 500 is 'normal' from https://docs.ceph.com/en/latest/dev/mon-osdmap-prune/

Can be related to this bug:
https://tracker.ceph.com/issues/44184

Doesn't exist on luminous so needs to gracefully degrade if data is not there (plus sometimes its not valid json if its run on an osd node)

**Comment by dosaboy** [comment]
@lathiat can you tell me where that information would be found in a sosreport?

**Comment by hillpd** [comment]
You can get it from `ceph report` within a sosreport.

As an example:
`ceph report | jq '.osdmap_manifest.pinned_maps | length'`
